<?php

namespace Database\Seeders;

use App\Domains\Admin\Models\AdminUser;
use App\Domains\Booking\Enums\BookingStatus;
use App\Domains\Booking\Enums\PaymentStatus;
use App\Domains\Booking\Enums\PaymentType;
use App\Domains\Booking\Models\Booking;
use App\Domains\Commute\Enums\CommuteAudience;
use App\Domains\Commute\Enums\CommuteDirection;
use App\Domains\Commute\Enums\CommuteLocationType;
use App\Domains\Commute\Enums\CommuteOfferStatus;
use App\Domains\Commute\Enums\CommuteType;
use App\Domains\Commute\Enums\ScheduledTripStatus;
use App\Domains\Commute\Models\CommuteLocation;
use App\Domains\Commute\Models\CommuteOffer;
use App\Domains\Commute\Models\CommuteSchedule;
use App\Domains\Commute\Models\ScheduledTrip;
use App\Domains\Commute\Support\DepartureTimeCalculator;
use App\Domains\Driver\Enums\VehicleVerificationStatus;
use App\Domains\Driver\Models\DriverProfile;
use App\Domains\Driver\Models\Vehicle;
use App\Domains\Geo\Models\Corridor;
use App\Domains\Geo\Models\Place;
use App\Domains\Identity\Enums\AccountStatus;
use App\Domains\Identity\Enums\OrgType;
use App\Domains\Identity\Enums\ProfileStatus;
use App\Domains\Identity\Enums\RegisteredRole;
use App\Domains\Identity\Models\Organization;
use App\Domains\Identity\Models\User;
use App\Domains\Matching\Models\CommuteDemand;
use App\Domains\Matching\Models\SavedSearch;
use App\Domains\Rating\Actions\RevealRatingsAction;
use App\Domains\Rating\Actions\SubmitRatingAction;
use App\Domains\Shared\ValueObjects\Coordinate;
use App\Domains\Shared\ValueObjects\DaysMask;
use App\Domains\Trip\Enums\TripSessionStatus;
use App\Domains\Trip\Models\TripSession;
use App\Domains\Verification\Enums\PublicTrustTier;
use App\Domains\Verification\Enums\VerificationType;
use App\Domains\Verification\Models\TrustScore;
use App\Domains\Verification\Models\UserVerification;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use RuntimeException;

/**
 * Data broad enough that the mobile team can open any screen and find something in it.
 *
 * 🔴 Why this is separate from `DatabaseSeeder` rather than folded into it. That one builds the
 * Bible's reference scenario — ONE driver, ONE passenger, ONE commute — and it is right to stay
 * that way: it is the story the documentation describes and the tests reason about. But one commute
 * means search returns a single result, nobody has a rating, and half the screens render an empty
 * state. A client developer cannot tell "the endpoint works and the list is empty" from "the
 * endpoint is broken", and will spend a day on the wrong one.
 *
 * So this runs that scenario first and then adds breadth around it:
 *
 *   · five more approved drivers with published commutes on the same corridor, at different
 *     prices, departure times, seat counts and audiences — so search ranks a real list and the
 *     score breakdown on screen 12 has something to break down
 *   · a fortnight of scheduled days for every one of them, generated by the REAL command rather
 *     than hand-written rows, so the horizon, the booking deadlines and the UTC conversion are
 *     whatever production would have produced
 *   · a journey that already happened, rated by both sides and revealed — which is the only way
 *     `avg_rating_as_driver` becomes a number, and therefore the only way the stars on search
 *     results, match details and the group member list stop being `null`
 *   · a saved search and a commute request for the demo passenger, so those two screens are not
 *     empty either
 *
 * 🔒 Everything here is obviously fictional: Arabic given names, `example` email domains, and
 * phone numbers in a block nobody owns. No real person's data belongs in a seeder — it ends up in
 * screenshots, in bug reports, and in whatever database somebody copies to their laptop.
 *
 * Run it with:  php artisan db:seed --class=DemoDataSeeder --force
 */
class DemoDataSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * The extra drivers. Varied on purpose: the match score weighs price, walking distance,
     * timing and trust, so a list where every row scores the same teaches the client nothing about
     * how to display it.
     *
     * @var list<array<string, mixed>>
     */
    private const DRIVERS = [
        ['name' => 'هالة سمير', 'first' => 'هالة', 'phone' => '+201055550001', 'time' => '06:50:00', 'price' => 7000, 'seats' => 3, 'plate' => 'ر س 118', 'make' => 'Hyundai', 'model' => 'Tucson', 'colour' => 'أبيض', 'trips' => 142, 'onTime' => 94.0, 'audience' => CommuteAudience::WomenOnly],
        ['name' => 'منى عبد الله', 'first' => 'منى', 'phone' => '+201055550002', 'time' => '07:15:00', 'price' => 9000, 'seats' => 4, 'plate' => 'ل م 307', 'make' => 'Toyota', 'model' => 'Corolla', 'colour' => 'رمادي', 'trips' => 58, 'onTime' => 88.0, 'audience' => CommuteAudience::WomenOnly],
        ['name' => 'سلمى فؤاد', 'first' => 'سلمى', 'phone' => '+201055550003', 'time' => '07:30:00', 'price' => 6500, 'seats' => 3, 'plate' => 'ن ه 952', 'make' => 'Nissan', 'model' => 'Sunny', 'colour' => 'أزرق', 'trips' => 11, 'onTime' => 100.0, 'audience' => CommuteAudience::WomenOnly],
        ['name' => 'داليا رأفت', 'first' => 'داليا', 'phone' => '+201055550004', 'time' => '06:40:00', 'price' => 11000, 'seats' => 2, 'plate' => 'ص ع 673', 'make' => 'Jeep', 'model' => 'Compass', 'colour' => 'أسود', 'trips' => 231, 'onTime' => 96.0, 'audience' => CommuteAudience::AnyVerified],
        // Deliberately unrated: a new driver is a state the client must render, and `null` must
        // never be drawn as nought stars.
        ['name' => 'ياسمين طارق', 'first' => 'ياسمين', 'phone' => '+201055550005', 'time' => '07:45:00', 'price' => 8000, 'seats' => 4, 'plate' => 'و ي 240', 'make' => 'Kia', 'model' => 'Cerato', 'colour' => 'أحمر', 'trips' => 0, 'onTime' => null, 'audience' => CommuteAudience::WomenOnly],
    ];

    public function run(): void
    {
        if (User::query()->exists()) {
            throw new RuntimeException(
                "This database already has accounts in it.\n\n"
                ."  · Rebuild a disposable environment:  php artisan migrate:fresh --seed --force --seeder=Database\\\\Seeders\\\\DemoDataSeeder\n\n"
                .'⚠️  `migrate:fresh` DROPS EVERY TABLE. Be certain which database this is first.'
            );
        }

        // The reference story first — this seeder adds to it rather than replacing it.
        $this->call(DatabaseSeeder::class);

        $admin = AdminUser::query()->firstOrFail();
        $organization = Organization::query()->firstOrFail();
        $corridor = Corridor::query()->firstOrFail();
        $origin = Place::query()->where('name', 'like', '%الرحاب%')->first() ?? Place::query()->firstOrFail();
        $destination = Place::query()->where('id', '!=', $origin->id)->firstOrFail();

        foreach (self::DRIVERS as $spec) {
            $this->seedDriverWithCommute($spec, $organization, $admin, $corridor, $origin, $destination);
        }

        /*
         * The real generator, not hand-written rows. It is what production runs every morning, so
         * the horizon length, the 21:00 booking deadlines and the local-to-UTC conversion are
         * whatever production would actually produce — including for the DST edge the Bible
         * spends a section on. Hand-building fourteen days per offer would be fourteen chances to
         * get that subtly wrong in a way only the mobile team would notice.
         */
        $this->command?->call('commutes:generate-trips');

        $mariam = User::query()->where('phone_e164', '+201033334444')->firstOrFail();

        $this->seedRatedJourney($mariam);
        $this->seedPassengerIntent($mariam, $origin, $destination);

        $this->announce();
    }

    /**
     * One approved driver with an active vehicle and a published recurring commute.
     *
     * @param  array<string, mixed>  $spec
     */
    private function seedDriverWithCommute(
        array $spec,
        Organization $organization,
        AdminUser $admin,
        Corridor $corridor,
        Place $origin,
        Place $destination,
    ): void {
        $driver = User::factory()->woman()->create([
            'phone_e164' => $spec['phone'],
            'full_name' => $spec['name'],
            'public_first_name' => $spec['first'],
            'org_type' => OrgType::Work,
            'organization_id' => $organization->id,
            'registered_role' => RegisteredRole::Driver,
            'account_status' => AccountStatus::Active,
            'profile_status' => ProfileStatus::BasicComplete,
            'trust_level' => 3,
        ]);

        // Three approved levels: enough to clear a `min_trust_level` of 3, which is what the
        // reference commute asks for, without pretending everybody is fully verified.
        foreach ([VerificationType::Phone, VerificationType::GovernmentId, VerificationType::Selfie] as $type) {
            UserVerification::factory()->approved()->create([
                'user_id' => $driver->id,
                'type' => $type,
                'reviewed_by' => $admin->id,
            ]);
        }

        TrustScore::factory()->create([
            'user_id' => $driver->id,
            'score' => 70,
            'public_tier' => PublicTrustTier::Trusted,
        ]);

        $profile = DriverProfile::factory()->approved()->create([
            'user_id' => $driver->id,
            'reviewer_id' => $admin->id,
            'completed_trips_count' => $spec['trips'],
            'cancellation_rate' => 1.50,
            'on_time_rate' => $spec['onTime'],
        ]);

        $vehicle = Vehicle::factory()->create([
            'driver_profile_id' => $profile->user_id,
            'make' => $spec['make'],
            'model' => $spec['model'],
            'year' => 2020,
            'colour' => $spec['colour'],
            'plate_number' => $spec['plate'],
            'plate_normalized' => Vehicle::normalizePlate($spec['plate']),
            'seats' => $spec['seats'] + 1,
            'is_active' => true,
            'verification_status' => VehicleVerificationStatus::Approved,
        ]);

        $offer = CommuteOffer::create([
            'driver_profile_id' => $profile->user_id,
            'vehicle_id' => $vehicle->id,
            'corridor_id' => $corridor->id,
            'commute_type' => CommuteType::Recurring,
            'status' => CommuteOfferStatus::Published,
            'direction' => CommuteDirection::ToWork,
            'seats_total' => $spec['seats'],
            'price_per_seat_piastres' => $spec['price'],
            'max_detour_minutes' => 12,
            'max_walk_minutes' => 12,
            'audience' => $spec['audience'],
            'allows_custom_pickup' => true,
            'route_polyline' => '}_p~iF~ps|U_ulL',
            'route_distance_meters' => 32000,
            'route_duration_seconds' => 2880,
            /*
             * The same box as the reference commute. It has to CONTAIN the search origin and
             * destination or the bounding-box pre-filter removes the offer before anything is
             * scored — which would make this seeder look like a broken search.
             */
            'bbox_min_lat' => 30.02,
            'bbox_max_lat' => 30.08,
            'bbox_min_lng' => 31.00,
            'bbox_max_lng' => 31.49,
            'published_at' => now(),
        ]);

        foreach ([
            [$origin, CommuteLocationType::Origin, 'الرحاب، بوابة ٢', 0],
            [$destination, CommuteLocationType::Destination, 'القرية الذكية، مبنى B6', 999],
        ] as [$place, $type, $address, $sequence]) {
            CommuteLocation::create([
                'commute_offer_id' => $offer->id,
                'place_id' => $place->id,
                'type' => $type,
                'point' => new Coordinate(lat: $place->lat, lng: $place->lng),
                'lat' => $place->lat,
                'lng' => $place->lng,
                'address' => $address,
                'sequence' => $sequence,
            ]);
        }

        CommuteSchedule::create([
            'commute_offer_id' => $offer->id,
            'days_mask' => DaysMask::weekdaysSunToThu()->value,
            'departure_time' => $spec['time'],
            'timezone' => 'Africa/Cairo',
            'start_date' => now()->toDateString(),
            'end_date' => now()->addMonths(4)->toDateString(),
        ]);
    }

    /**
     * 🔴 A journey that already happened, rated by both sides and revealed.
     *
     * This is the only way a rating becomes visible to anybody: `visible_at` is filled when both
     * parties have rated or the window passes, and `avg_rating_as_driver` is recomputed only on
     * that reveal. Without one of these, every `rating` in every payload is `null` — which is
     * correct, and indistinguishable from a broken field to somebody building the screen.
     *
     * Driven through the real Actions rather than by inserting rows, so the reveal, the pairing and
     * the recomputed average are produced by the code the API runs.
     */
    private function seedRatedJourney(User $mariam): void
    {
        $offer = CommuteOffer::query()
            ->whereHas('schedule')
            ->with('schedule', 'vehicle')
            ->first();

        if ($offer === null) {
            return;
        }

        $schedule = $offer->schedule;

        // Two days ago, so it is inside the seven-day rating window.
        $tripDate = now()->subDays(2)->toDateString();

        $trip = ScheduledTrip::create([
            'commute_offer_id' => $offer->id,
            'commute_schedule_id' => $schedule->id,
            'trip_date' => $tripDate,
            'departure_at' => DepartureTimeCalculator::toUtc($tripDate, $schedule->departure_time, $schedule->timezone),
            'departure_local' => "{$tripDate} {$schedule->departure_time}",
            'seats_total' => $offer->seats_total,
            'seats_taken' => 1,
            'price_snapshot_piastres' => $offer->price_per_seat_piastres,
            'status' => ScheduledTripStatus::Completed,
            'booking_deadline_at' => now()->parse($tripDate)->subDay()->setTime(21, 0),
        ]);

        TripSession::create([
            'scheduled_trip_id' => $trip->id,
            'current_status' => TripSessionStatus::Completed,
            'started_at' => $trip->departure_at,
            'completed_at' => $trip->departure_at->copy()->addMinutes(48),
        ]);

        $booking = Booking::create([
            'scheduled_trip_id' => $trip->id,
            'passenger_user_id' => $mariam->id,
            'driver_profile_id' => $offer->driver_profile_id,
            'seats_reserved' => 1,
            'price_snapshot_piastres' => $offer->price_per_seat_piastres,
            'platform_fee_snapshot_piastres' => 0,
            'driver_amount_snapshot_piastres' => $offer->price_per_seat_piastres,
            'payment_type' => PaymentType::Cash,
        ]);

        $booking->forceFill([
            'status' => BookingStatus::Completed->value,
            'payment_status' => PaymentStatus::NotDue->value,
        ])->save();

        $driver = User::query()->whereKey($offer->driver_profile_id)->firstOrFail();

        $ratings = app(SubmitRatingAction::class);

        $ratings->submit($mariam, $booking->refresh(), [
            'stars' => 5,
            'comment' => 'سواقة هادية جدًا والمواعيد مظبوطة. أول مرة أركب وحسّيت إني مرتاحة.',
            'tags' => ['safe_driving', 'on_time', 'clean_car'],
        ]);

        // The second submission completes the pair, which is what reveals both.
        $ratings->submit($driver, $booking->refresh(), [
            'stars' => 5,
            'comment' => 'راكبة محترمة وملتزمة بالمواعيد.',
            'tags' => ['great_company', 'on_time'],
        ]);

        // Belt and braces: the pair reveal already ran inside `submit`, and calling it again is a
        // no-op that also recomputes the averages if anything above changed order.
        app(RevealRatingsAction::class)->pair($booking->refresh());
    }

    /**
     * A saved search and a standing commute request, so screens 11 and 18 are not empty.
     */
    private function seedPassengerIntent(User $mariam, Place $origin, Place $destination): void
    {
        $filters = [
            'origin' => ['lat' => $origin->lat, 'lng' => $origin->lng],
            'destination' => ['lat' => $destination->lat, 'lng' => $destination->lng],
            'daysMask' => DaysMask::weekdaysSunToThu()->value,
            'arrivalWindowStart' => '06:45:00',
            'arrivalWindowEnd' => '08:00:00',
            'maxWalkMinutes' => 12,
            'maxDetourMinutes' => 15,
        ];

        SavedSearch::factory()->create([
            'user_id' => $mariam->id,
            'title' => 'الرحاب ← القرية الذكية',
            'filters' => $filters,
        ]);

        /*
         * Only the owner is overridden. The factory already builds a coherent demand — the two
         * points, their labels, the arrival window, the audience preference — and restating any of
         * it here is a second place for the shape to drift from the schema. That is exactly how the
         * first attempt at this line failed: it passed `user_id`, `origin_place_id` and
         * `destination_place_id`, none of which are columns on this table.
         */
        CommuteDemand::factory()->create([
            'passenger_user_id' => $mariam->id,
            'days_mask' => DaysMask::weekdaysSunToThu()->value,
        ]);
    }

    private function announce(): void
    {
        $command = $this->command;

        if ($command === null) {
            return;
        }

        $command->newLine();
        $command->info('Demo data seeded.');
        $command->line('  commutes published: '.CommuteOffer::query()->where('status', CommuteOfferStatus::Published)->count());
        $command->line('  scheduled days:     '.ScheduledTrip::query()->count());
        $command->line('  drivers:            '.DriverProfile::query()->count());
        $command->newLine();
        $command->line('🔑 To sign in from the app without an SMS provider, set this and redeploy:');
        $command->line('      RAFEEQ_DEV_OTP_CODE=123456');
        $command->line('   then request a code for any of the phones below and enter 123456.');
        $command->line('   It is refused outright on APP_ENV=production, so it cannot ship by accident.');
        $command->newLine();
        $command->line('   +201033334444  Mariam — passenger: bookings, a rated trip, a saved search');
        $command->line('   +201011112222  Nour   — driver: published commute, group, pending requests');
        $command->newLine();
    }
}
