<?php

namespace Database\Factories;

use App\Domains\Admin\Enums\AdminStatus;
use App\Domains\Admin\Models\AdminUser;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;

/**
 * @extends Factory<AdminUser>
 */
class AdminUserFactory extends Factory
{
    protected $model = AdminUser::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->unique()->safeEmail(),
            'password_hash' => Hash::make('password'),
            // A real TOTP secret is generated by the MFA setup Action
            // (Phase 13) — this is just a placeholder for tests/seeding.
            'mfa_secret' => bin2hex(random_bytes(16)),
            'mfa_confirmed_at' => now(),
            'status' => AdminStatus::Active,
        ];
    }

    public function suspended(): static
    {
        return $this->state(fn (array $attributes) => ['status' => AdminStatus::Suspended]);
    }
}
